# v2 setup component test
include:
  - component: $CI_SERVER_FQDN/Fortify/components/fcli/linux@2
    inputs:
      stage: test

fcli:                        # Needs to match the job name specified above
  script:
    - uname -a               
    - ${FCLI} -V             
    
  variables:
    FCLI_URL: ${FCLI_URL}
