# v2 FoD ast-scan component test
include:
  - component: $CI_SERVER_FQDN/Fortify/components/ast-scan/linux@1
    inputs:
      debug: true
      fcli-version: ${FCLI_VERSION}

fortify-ast-scan:
  image: ${GITLAB_IMAGE}
  variables:
    SOURCE_DIR: ${CI_PROJECT_DIR}/${SOURCE_DIR}
    FOD_URL: ${FCLI_FT_FOD_URL}
    FOD_CLIENT_ID: ${FCLI_FT_FOD_CLIENT_ID}
    FOD_CLIENT_SECRET: ${FCLI_FT_FOD_CLIENT_SECRET}
    FOD_RELEASE: ${FORTIFY_RELEASE}
    DO_SCA_SCAN: true
    DO_AVIATOR_AUDIT: true
    OVERRIDE_SAST_SETTINGS: true
